### ISSUE TITLE
Option to hide or change the navigation arrows on bottom right of slides

### ISSUE THREAD

**Issue by rleyvasal** [rstudio/revealjs#110]
I would like to have the option to hide or change the shape of the navigation arrows on the bottom right of the slides to increase my slide presentation area. 

I did not find any information about it on the [bookdown](https://bookdown.org/yihui/rmarkdown/revealjs.html) documentation.

Default navigation Arrows shown below:
<img width="131" alt="navigation_arrows" src="https://user-images.githubusercontent.com/61335136/133479087-70509a5e-6b78-4028-b3c7-1c01cc9a5c87.PNG">

**Comment by cderv** [comment]
This is already something you can do using Reveal options: https://revealjs.com/config/

Those options can be passed using `reveal_options` argument in the format function

````yaml
output: 
  revealjs::revealjs_presentation:
    reveal_options: 
      controls: false
````

I don't think we supported (yet) all documented options (like `controlsLayout` or `controlsBackArrows` in the link page) because this package does not shipped with the latest reveal.js lib but most of them should work. 

Please reopen this issue if this is not working for you.
