### ISSUE TITLE
Support for reveal.js fragments in rmarkdown

### ISSUE THREAD

**Issue by jlegewie** [rstudio/revealjs#44]
A popular Reveal.js feature is "Fragments" – the ability to show/hide text after the initial display of the slide. Basically incremental slides but not globally for the entire slide deck and with more fine-grained control. When you use markdown (not rmarkdown) to create a reveal.js slideshow you can use this syntax
```
<!-- .element: class="fragment" -->
```

It's also possible to target the entire slide and add attributes to it:

```
<!-- .slide: data-background-image="resources/my-background.jpg" -->
```

This is all described [here](https://stevegrunwell.com/blog/building-presentations-reveal-js/). Would be great if the RMarkdown would support these features as well!

**Comment by jjallaire** [comment]
You can in fact accomplish much of what you are suggesting already.
Incremental bullets can be created using the ">" prefix:
http://rmarkdown.rstudio.com/revealjs_presentation_format.html#incremental_bullets

You can use the markdown header attribute block (i.e. {}) to add attributes
to slides:
http://rmarkdown.rstudio.com/revealjs_presentation_format.html#slide_backgrounds

If you want to apply the fragment class to a given paragraph just wrap it
in a div or a span.

**Comment by nevrome** [comment]
Just came across this problem and thought I could add an example: 


```
## cucumber

<div class="fragment" data-fragment-index="2">
- bread
</div>

\

<div class="fragment" data-fragment-index="1">
- cheese
     - cake
     - sandwich
     - ...
</div>

\

<div class="fragment" data-fragment-index="3">
- **eggs**
    - tomato
    - banana
</div>

```

**Comment by RGiuseppe** [comment]
Hello everyone, I found another way to use the fragments, you can use a h7 header (yes 7) followed by the "fragment class"

`####### "your text here" {.fragment}`

**Comment by fervilber** [comment]
RGiuseppe it works great, but how can I indicate the type of fragments ( for example grow or fade-up)??

**Comment by RGiuseppe** [comment]
sorry fervilber, I haven't received notifications, I know it's been a long time, but if you still need it you can do it like this:

> `####### "your text here" {.fragment .grow}'
> '####### "your text here" {.fragment .fade-up}'
> '####### "your text here" {.fragment .highlight-blue}'

**Comment by RGiuseppe** [comment]
sorry fervilber, I haven't received notifications, I know it's been a long time, but if you still need it you can do it like this:
```
####### "your text here" {.fragment .grow}

####### "your text here" {.fragment .fade-up}

####### "your text here" {.fragment .highlight-blue}
```

**Comment by joymon** [comment]
- test {.fragment}

The above is simply working for me. No need of 7 headers :). I am using the VSCode extension to code and its server to present.

**Comment by cderv** [comment]
I will close this issue because this is already working as expected. There is several ways to to the fragment feature from reveal.js with R Markdown and Pandoc

- Using pausing mechanism (https://pandoc.org/MANUAL.html#inserting-pauses) 
  This will use the `fragment` class of reveal 
  ````markdown
  # Pausing using pandoc syntax

  content before the pause
  
  . . .
  
  content after the pause
  
  . . .
  
  Content after another pause
  ````
- Using incremental list (https://pandoc.org/MANUAL.html#incremental-lists)
  This will also use the `fragment` feature from Pandoc by putting the class on the `<li>` element
  * When using `incremental: true` under `revealjs::revealjs_presentation:`, all list will be incremental
    ```markdown
    ## list 
  
    - item 1
    - item 2
    ```
  	Can be disable locally by using `.nonincremental` class on a div (using fenced div)
    ```markdown
    ## Non Incremental list

   ::: nonincremental
   
   - Eat spaghetti
   - Drink wine
   
   :::
   ```
 * When using `incremental: false`, it can be activated using `.incremental` class 
    ```markdown
    ## Incremental list

   ::: incremental
   
   - Eat spaghetti
   - Drink wine
   
   :::
   ```
- Using the `.fragment` class with Pandoc's [Fenced Divs Attributes](https://pandoc.org/MANUAL.html#extension-fenced_divs) and [bracketed spans](https://pandoc.org/MANUAL.html#extension-bracketed_spans)
  ```markdown
  # Equivalent to using fenced div
  
  Content before fade
  
  ::: fragment
  content after the pause
  :::
  
  ::: fragment
  content after the pause
  :::
  
  # attributes can be added on divs
  
  ::: fragment
  Fade in
  :::
  
  ::: {.fragment .fade-out}
  Fade out
  :::
  
  ::: {.fragment .highlight-red}
  Highlight red
  :::
  
  ::: {.fragment .current-visible}
  Fade in, then out
  :::

  # Working on spans too 

  [Fade in]{.fragment}
  
  [Fade out]{.fragment .fade-out}
  
  [Highlight red]{.fragment .highlight-red}
  
  [Fade in, then out]{.fragment .current-visible}
  
  [Slide up while fading in]{.fragment .fade-right}
  ```

Relevant issue which explore the different syntax possible for documentation is #120

i'll close this one
