### ISSUE TITLE
content associated with top-level elements is dropped

### ISSUE THREAD

**Issue by aronatkins** [rstudio/revealjs#52]
```
---
title: "reveal.js"
output: revealjs::revealjs_presentation
---

# In the morning

- we say something
- we say something else
```

The `In the morning` slide contains no content.

The generated HTML for the slides:

```
<section>
    <h1 class="title">reveal.js</h1>
</section>

<section><section id="in-the-morning" class="titleslide slide level1"><h1>In the morning</h1></section></section>
```

I expected something more like:

```
      <section>
        <h1 class="title">reveal.js</h1>
      </section>

      <section id="in-the-morning" class="titleslide slide level1">
        <h1>In the morning</h1>
        <ul>
          <li>we say something</li>
          <li>we say something else</li>
        </ul>
      </section>
```

**Comment by aronatkins** [comment]
Workaround is to use `##` markers instead of `#` markers.

**Comment by jjallaire** [comment]
That's because reveal.js uses level 1 headers for vertical navigation (level 2 headers are the default for slides, see docs here: https://github.com/rstudio/revealjs#2-d-presenations). If you change your code as follows it will work as expected:

```
---
title: "reveal.js"
output: 
  revealjs::revealjs_presentation:
      slide_level: 1
---

# In the morning

- we say something
- we say something else
```

**Comment by aronatkins** [comment]
I actually narrowed this from something that had both level1 and level2 headers.

```
# In the morning

- we say something
- we say something else

## Getting up

- Turn off alarm
- Get out of bed

## Breakfast

- Eat eggs
- Drink coffee

# In the evening

- The day is near an end
- Darkness is coming

## Dinner

- Eat spaghetti
- Drink wine

## Going to sleep

- Get in bed
- Count sheep
```

**Comment by jjallaire** [comment]
That's correct. Slide heading pages don't support content.

**Comment by aronatkins** [comment]
I was trying to simulate what I would get with the raw reveal.js code:

```
<section>
  <section>
    <h2>first child</h2>
    <p>this is some child content</p>
  </section>
  <section>
    <h2>second child</h2>
    <p>this is some child content</p>
  </section>
</section>

<section>
  <section>
    <h2>first child</h2>
    <p>this is some child content</p>
  </section>
  <section>
    <h2>second child</h2>
    <p>this is some child content</p>
  </section>
</section>
```

If you plug that into the reveal.js HTML template, you'll see that there's nothing that corresponds to the level1 blank page. There are two left-to-right slides and each has one down slide.

**Comment by jjallaire** [comment]
I still don't quite understand the issue for the revealjs package. We're literally just handing the markdown to pandoc and relying on the default reveal.js CSS. If there is an issue it is perhaps with how pandoc handles the markdown to reveal translation by default? Or perhaps it's with the reveal.js CSS around horizontal header pages?

So unless I'm missing something I don't know what else to do if the pandoc handling isn't as desired. We could try to implement a local workaround but I probably don't have time to do that right now.

I could be missing something entirely and the issue is something introduced by the revealjs R package, but as far as I know we are an extremely thin layer over pandoc so the issue is likely there.

**Comment by aronatkins** [comment]
This looks to be the same as https://github.com/rstudio/revealjs/issues/40, which has a suggested workaround. You're right; this looks like a problem with the translation by pandoc.
